### ISSUE TITLE
Oauth2 Crash

### ISSUE THREAD

**Issue by tdameros** [tdameros/42-transcendence#107]
Oauth2 endpoints do not work, there is an error 500.
Here are the problems I've identified:

- Doc not up to date (URL)
- No tests
- Error 500

**Comment by aLeuleu** [comment]
Please explain what is the bug. as for the test is normal that they are no tests because it's a very hard feature to test but if you know how to do it, maybe you can show me . please add screenshots or explain. What did you do in order to produce the bug

**Comment by tdameros** [comment]
I just made a GET request on the endpoint

**Comment by aLeuleu** [comment]
https://github.com/tdameros/42-transcendence/pull/128
