### ISSUE TITLE
Remove 400 for /user/signin/

### ISSUE THREAD

**Issue by tdameros** [tdameros/42-transcendence#114]
I think it's important to remove the status code 400 on signin when a username is not known because it triggers warnings in the browser. The subject asks us not to have warnings on the front-end.

<img width="590" alt="Screenshot 2024-01-29 at 11 45 32" src="https://github.com/tdameros/42-transcendence/assets/50496792/9197f7ed-fb47-446b-8f3e-15ee624adba6">

**Comment by tdameros** [comment]
I've asked the bocal and I'm waiting for an answer.

**Comment by aLeuleu** [comment]
The front end should prevent the user, sending a request if the sign form is not correct. Therefore, you should never see what you put in the screenshot. The errors you see in the screenshot should only be seen by someone using the API
