### ISSUE TITLE
Create tournament endpoint

### ISSUE THREAD

**Issue by EthanDelage** [tdameros/42-transcendence#22]

**Comment by EthanDelage** [comment]
Error with this request:
```
POST /tournament

{
    "name": "test",
    "is-private": false,
    "registration-deadline": "2023-12-31T00:10:00"
}
```

Error message: `can't compare offset-naive and offset-aware datetimes`

**Comment by aLeuleu** [comment]
> Error with this request:
> 
> ```
> POST /tournament
> 
> {
>     "name": "test",
>     "is-private": false,
>     "registration-deadline": "2023-12-31T00:10:00"
> }
> ```
> 
> Error message: `can't compare offset-naive and offset-aware datetimes`

This error message seems to appear when you compare a date with a time zone information,(offset-aware) and a date without any time zone information (offset-naive).

Example of offset-aware date : `datetime.datetime(2023, 1, 1, 12, 0, 0, tzinfo=timezone.utc)`
Example of offset-naive date : `datetime.datetime(2023, 1, 1, 12, 0, 0)`

So : be consistent with the timezone ( be sure to use it everywhere)
