### ISSUE TITLE
Find match when not logged in

### ISSUE THREAD

**Issue by V-Fries** [tdameros/42-transcendence#242]
When not logged in you can still press find match:
- The client tries to connect to matchmaking without a token
- The connection is refused
- Client attempts generating a token (POST /user/refresh-access-jwt/)
- Request fails, error is printed

Maybe redirect to the login page when not logged in?

**Comment by tdameros** [comment]
Yes, there are a few pages that are not yet secure. Thanks for your feedback, I'll fix that in a future PR.
