### ISSUE TITLE
Create common folder

### ISSUE THREAD

**Issue by tdameros** [tdameros/42-transcendence#34]

**Comment by tdameros** [comment]
Add logger in common folder

**Comment by tdameros** [comment]
Add JWTManager in common folder

**Comment by tdameros** [comment]
Add microservices URLs

**Comment by tdameros** [comment]
> Add microservices URLs

Maybe something other than python variables for URLs, as I'd also need them in JS for the single page application.

**Comment by aLeuleu** [comment]
The `Good first issue` is supposed to help newcomers that just arrived at the project find an easy issue to solve.
We should change or edit the label
