### ISSUE TITLE
500 in oauth

### ISSUE THREAD

**Issue by aLeuleu** [tdameros/42-transcendence#448]
500 : 
https://42.shiftcode.fr:6002/user/oauth/callback/github/?code=91bea0e29b447c1a53&state=Rlz1cM1AZwP0Rfmqw3SxW7brp0dvnVq8AZP33JuwcHn6P4QMHKhgROmZn8p7RtIQL5jv0G4fVG6rcIqcrysSo1W14CCQtKyLfUuhK1VI7i49IGkcXks4oN0TYg5oZxxLh0QEuD87cH01ScdDUru49pHVWxIPrYVy2oCkN2yNK8jqX9KzGGQeXQve35XpMAqwuwGvZeKLRF4PUEShAxlcIYwglVAXDblLd24zwemg7YsRBjBmcUFKzfHUn9xvv

**Comment by tdameros** [comment]
https://42.shiftcode.fr:6002/user/oauth/callback/bidule/
