### ISSUE TITLE
500 during login

### ISSUE THREAD

**Issue by tdameros** [tdameros/42-transcendence#470]
<img width="771" alt="Screenshot 2024-03-07 at 23 04 26" src="https://github.com/tdameros/42-transcendence/assets/50496792/08888d3f-60c6-4631-9343-8ffbb7a6f5f5">

**Comment by aLeuleu** [comment]
Unable to reproduce the bug in local mode. Please give access to production `user-management-db` and `user-management`

**Comment by tdameros** [comment]
The error came from the fact that I was trying to connect to an account that didn't have a password because it had been created with oauth.
However, when connecting, the signin view tried to checkpassword a None password.
