### ISSUE TITLE
Error when "make generate_env"

### ISSUE THREAD

**Issue by Bourdon94m** [tdameros/42-transcendence#533]
Hello !

Petit soucis sur ma machine en essayant de test le projet avec la commande : "make generate_env". 
Cela me met comme erreur qu'il n'arrive pas a trouver des modules py. 

![image](https://github.com/user-attachments/assets/ec42df3a-a825-4d9a-87da-96277757080c)

**Comment by tdameros** [comment]
Hello 👋 

Il faut que tu installes les modules python qui se trouvent dans **common/docker/requirements.txt** :


`pip3 install -r common/docker/requirements.txt`

**Comment by a-levra** [comment]
Pour ceux qui ont le même problème et qui ont la sensation d'avoir déja installé les paquets : 
Ne pas oublier de se mettre dans un environnement virtuel :
```cd 42-transcendence
python3.11 -m venv .venv
source .venv/bin/activate
```

et après on peut installer les requirements comme décris dans le readme ( d'ailleurs, peut-ê rajotuer dans le readme qu' il faut se mettre dans un venv ..? )
